import { useEffect, useMemo, useState } from 'react'
import type { RuntimeComponent, RuntimeConfigDraft, RuntimeInventory } from '../../../../shared/industry/runtime'
import { RUNTIME_COMPONENTS } from '../../../../shared/industry/runtime'
import { createP10ApiClient, type P10ApiClient } from '../../api/p10-client'
import './p10.css'

const defaultClient=createP10ApiClient()
export interface RuntimeSnapshot { inventory: RuntimeInventory; drafts: readonly RuntimeConfigDraft[]; selectedDraft?: RuntimeConfigDraft }

export function RuntimePage({client=defaultClient,initialSnapshot}:{client?:P10ApiClient;initialSnapshot?:RuntimeSnapshot}){
  const [snapshot,setSnapshot]=useState<RuntimeSnapshot|undefined>(initialSnapshot)
  const [component,setComponent]=useState<RuntimeComponent>('AGENT_MODEL')
  const [adapter,setAdapter]=useState('')
  const [endpointAlias,setEndpointAlias]=useState('')
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState<string|null>(null)
  useEffect(()=>{if(initialSnapshot!==undefined)return undefined;let cancelled=false;void load(client).then((value)=>{if(!cancelled)setSnapshot(value)}).catch((reason:unknown)=>{if(!cancelled)setError(messageOf(reason))});return()=>{cancelled=true}},[client,initialSnapshot])
  async function refresh(selectedDraft?:RuntimeConfigDraft){const [inventory,drafts]=await Promise.all([client.getRuntimeInventory(),client.listRuntimeConfigDrafts()]);setSnapshot({inventory,drafts,selectedDraft:selectedDraft??snapshot?.selectedDraft})}
  async function createDraft(){setBusy(true);setError(null);try{const change={component,...(adapter.trim()===''?{}:{adapter:adapter.trim()}),...(endpointAlias.trim()===''?{}:{endpointAlias:endpointAlias.trim()})};const draft=await client.createRuntimeConfigDraft({changes:[change]});await refresh(draft);setAdapter('');setEndpointAlias('')}catch(reason){setError(messageOf(reason))}finally{setBusy(false)}}
  async function act(kind:'validate'|'save'|'eval',draftId:string){setBusy(true);setError(null);try{const draft=kind==='validate'?await client.validateRuntimeConfigDraft(draftId):kind==='save'?await client.saveRuntimeConfigDraft(draftId):await client.evaluateRuntimeConfigDraft(draftId);await refresh(draft)}catch(reason){setError(messageOf(reason))}finally{setBusy(false)}}
  if(snapshot===undefined)return <main className="p10-page"><h1>Runtime</h1><p>{error??'Loading runtime inventory…'}</p></main>
  return <RuntimeView snapshot={snapshot} component={component} adapter={adapter} endpointAlias={endpointAlias} busy={busy} error={error} onComponent={setComponent} onAdapter={setAdapter} onEndpointAlias={setEndpointAlias} onCreate={()=>void createDraft()} onSelect={(draft)=>setSnapshot((value)=>value===undefined?value:{...value,selectedDraft:draft})} onAction={(kind,id)=>void act(kind,id)}/>
}

export function RuntimeView({snapshot,component,adapter,endpointAlias,busy,error,onComponent=()=>undefined,onAdapter=()=>undefined,onEndpointAlias=()=>undefined,onCreate=()=>undefined,onSelect=()=>undefined,onAction=()=>undefined}:{snapshot:RuntimeSnapshot;component:RuntimeComponent;adapter:string;endpointAlias:string;busy:boolean;error:string|null;onComponent?:(value:RuntimeComponent)=>void;onAdapter?:(value:string)=>void;onEndpointAlias?:(value:string)=>void;onCreate?:()=>void;onSelect?:(draft:RuntimeConfigDraft)=>void;onAction?:(kind:'validate'|'save'|'eval',draftId:string)=>void}){
  const selected=snapshot.selectedDraft??snapshot.drafts[0]
  const errors=selected?.validationIssues.filter((item)=>item.severity==='ERROR').length??0
  const components=useMemo(()=>new Set(snapshot.inventory.adapters.map((item)=>item.component)),[snapshot.inventory.adapters])
  return <main className="p10-page" aria-labelledby="runtime-title">
    <div className="p10-eyebrow">Runtime / Adapter · P10</div>
    <div className="p10-heading-row"><div><h1 id="runtime-title">Runtime</h1><p>Mock adapter inventory and versioned config draft flow. Secret values are never returned to the browser.</p></div><div><strong>Config v{snapshot.inventory.configVersion}</strong> · {snapshot.inventory.environment}</div></div>
    {error===null?null:<p role="alert" className="p10-error">{error}</p>}
    <section className="p10-panel"><h2>Adapter inventory</h2><table className="p10-table"><thead><tr><th>Component</th><th>Adapter</th><th>Endpoint alias</th><th>Configured</th><th>Health</th><th>Version</th><th>Last check</th><th>Secret source</th></tr></thead><tbody>{snapshot.inventory.adapters.map((item)=><tr key={item.component}><td><strong>{item.label}</strong><br/><code>{item.component}</code></td><td><code>{item.adapter}</code></td><td><code>{item.endpointAlias}</code></td><td>{item.configured?'yes':'no'}</td><td>{item.health}</td><td>{item.version}</td><td>{item.lastCheckAt}</td><td>{item.secret.source} · {item.secret.configured?'configured':'not configured'}{item.secret.reference===undefined?'':<><br/><code>{item.secret.reference}</code></>}</td></tr>)}</tbody></table><p>{components.size}/10 runtime components present.</p></section>
    <section className="p10-panel"><h2>Create config draft</h2><p>Editable fields are aliases only. URLs, credentials, secret values, project scope, and promotion flags are not part of this browser contract.</p><div className="p10-form"><label>Component<select value={component} disabled={busy} onChange={(event)=>onComponent(event.target.value as RuntimeComponent)}>{RUNTIME_COMPONENTS.map((item)=><option key={item} value={item}>{item}</option>)}</select></label><label>Adapter alias<input value={adapter} disabled={busy} placeholder="mock-agent-model-v2" onChange={(event)=>onAdapter(event.target.value)}/></label><label>Endpoint alias<input value={endpointAlias} disabled={busy} placeholder="agent-model-candidate" onChange={(event)=>onEndpointAlias(event.target.value)}/></label><button type="button" disabled={busy||(adapter.trim()===''&&endpointAlias.trim()==='')} onClick={onCreate}>Create Draft</button></div></section>
    <section className="p10-panel"><h2>Drafts</h2>{snapshot.drafts.length===0?<p>No config drafts yet.</p>:<table className="p10-table"><thead><tr><th>Draft</th><th>Base</th><th>Status</th><th>Saved</th><th>Eval</th><th>Eligible</th><th /></tr></thead><tbody>{snapshot.drafts.map((draft)=><tr key={draft.draftId} data-selected={selected?.draftId===draft.draftId}><td><code>{draft.draftId}</code></td><td>v{draft.baseVersion}</td><td>{draft.status}</td><td>{draft.savedVersion===undefined?'—':`v${draft.savedVersion}`}</td><td>{draft.evalResult?.status??'—'}</td><td>{draft.eligibleForPromote?'YES':'NO'}</td><td><button type="button" onClick={()=>onSelect(draft)}>Inspect</button></td></tr>)}</tbody></table>}</section>
    {selected===undefined?null:<section className="p10-panel" data-draft={selected.draftId}><div className="p10-heading-row"><div><h2>Config Draft Flow</h2><p><code>Draft → Validate → Diff → Save → version bump → Eval → eligible for promote</code></p></div><strong>{selected.status}</strong></div><div className="p10-actions">{selected.status==='DRAFT'?<button type="button" disabled={busy} onClick={()=>onAction('validate',selected.draftId)}>Validate</button>:null}{selected.status==='VALIDATED'?<button type="button" disabled={busy||errors>0} onClick={()=>onAction('save',selected.draftId)}>Save &amp; bump version</button>:null}{selected.status==='SAVED'?<button type="button" disabled={busy} onClick={()=>onAction('eval',selected.draftId)}>Run Eval</button>:null}</div><h3>Validation</h3>{selected.validationIssues.length===0?<p>No validation issues.</p>:<ul>{selected.validationIssues.map((item)=><li key={`${item.code}-${item.component??'global'}`}>{item.severity} · {item.code} · {item.message}</li>)}</ul>}<h3>Diff</h3>{selected.diff.length===0?<p>No diff generated yet.</p>:<table className="p10-table"><thead><tr><th>Component</th><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>{selected.diff.map((item)=><tr key={`${item.component}-${item.field}`}><td>{item.component}</td><td>{item.field}</td><td><code>{item.before}</code></td><td><code>{item.after}</code></td></tr>)}</tbody></table>}<h3>Eval / eligibility</h3><p>Eval: <strong>{selected.evalResult?.status??'not run'}</strong> · Eligible for promote: <strong>{selected.eligibleForPromote?'YES':'NO'}</strong></p>{selected.evalResult===undefined?null:<ul>{selected.evalResult.checks.map((item)=><li key={item.name}>{item.passed?'PASS':'FAIL'} · {item.name} · {item.detail}</li>)}</ul>}<p className="p10-note">P10 deliberately has no Promote action. P11 owns unified benchmark/release gating.</p></section>}
  </main>
}

async function load(client:P10ApiClient):Promise<RuntimeSnapshot>{const[inventory,drafts]=await Promise.all([client.getRuntimeInventory(),client.listRuntimeConfigDrafts()]);return{inventory,drafts,selectedDraft:drafts[0]}}
function messageOf(reason:unknown):string{return reason instanceof Error?reason.message:String(reason)}
