import { useEffect, useMemo, useState } from 'react'
import type { RuntimeComponent, RuntimeConfigDraft, RuntimeInventory } from '../../../../shared/industry/runtime'
import { RUNTIME_COMPONENTS } from '../../../../shared/industry/runtime'
import { createP10ApiClient, type P10ApiClient } from '../../api/p10-client'
import './p10.css'

const defaultClient=createP10ApiClient()
export interface RuntimeSnapshot { inventory: RuntimeInventory; drafts: readonly RuntimeConfigDraft[]; selectedDraft?: RuntimeConfigDraft }

export function RuntimePage({client=defaultClient,initialSnapshot}:{client?:P10ApiClient;initialSnapshot?:RuntimeSnapshot}){
  const [snapshot,setSnapshot]=useState<RuntimeSnapshot|undefined>(initialSnapshot)
  const [component,setComponent]=useState<RuntimeComponent>('AGENT_MODEL')
  const [adapter,setAdapter]=useState('')
  const [endpointAlias,setEndpointAlias]=useState('')
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState<string|null>(null)
  useEffect(()=>{if(initialSnapshot!==undefined)return undefined;let cancelled=false;void load(client).then((value)=>{if(!cancelled)setSnapshot(value)}).catch((reason:unknown)=>{if(!cancelled)setError(messageOf(reason))});return()=>{cancelled=true}},[client,initialSnapshot])
  async function refresh(selectedDraft?:RuntimeConfigDraft){const [inventory,drafts]=await Promise.all([client.getRuntimeInventory(),client.listRuntimeConfigDrafts()]);setSnapshot({inventory,drafts,selectedDraft:selectedDraft??snapshot?.selectedDraft})}
  async function createDraft(){setBusy(true);setError(null);try{const change={component,...(adapter.trim()===''?{}:{adapter:adapter.trim()}),...(endpointAlias.trim()===''?{}:{endpointAlias:endpointAlias.trim()})};const draft=await client.createRuntimeConfigDraft({changes:[change]});await refresh(draft);setAdapter('');setEndpointAlias('')}catch(reason){setError(messageOf(reason))}finally{setBusy(false)}}
  async function act(kind:'validate'|'save'|'eval',draftId:string){setBusy(true);setError(null);try{const draft=kind==='validate'?await client.validateRuntimeConfigDraft(draftId):kind==='save'?await client.saveRuntimeConfigDraft(draftId):await client.evaluateRuntimeConfigDraft(draftId);await refresh(draft)}catch(reason){setError(messageOf(reason))}finally{setBusy(false)}}
  if(snapshot===undefined)return <main className="p10-page"><h1>运行时</h1><p>{error??'正在加载运行时清单…'}</p></main>
  return <RuntimeView snapshot={snapshot} component={component} adapter={adapter} endpointAlias={endpointAlias} busy={busy} error={error} onComponent={setComponent} onAdapter={setAdapter} onEndpointAlias={setEndpointAlias} onCreate={()=>void createDraft()} onSelect={(draft)=>setSnapshot((value)=>value===undefined?value:{...value,selectedDraft:draft})} onAction={(kind,id)=>void act(kind,id)}/>
}

export function RuntimeView({snapshot,component,adapter,endpointAlias,busy,error,onComponent=()=>undefined,onAdapter=()=>undefined,onEndpointAlias=()=>undefined,onCreate=()=>undefined,onSelect=()=>undefined,onAction=()=>undefined}:{snapshot:RuntimeSnapshot;component:RuntimeComponent;adapter:string;endpointAlias:string;busy:boolean;error:string|null;onComponent?:(value:RuntimeComponent)=>void;onAdapter?:(value:string)=>void;onEndpointAlias?:(value:string)=>void;onCreate?:()=>void;onSelect?:(draft:RuntimeConfigDraft)=>void;onAction?:(kind:'validate'|'save'|'eval',draftId:string)=>void}){
  const selected=snapshot.selectedDraft??snapshot.drafts[0]
  const errors=selected?.validationIssues.filter((item)=>item.severity==='ERROR').length??0
  const components=useMemo(()=>new Set(snapshot.inventory.adapters.map((item)=>item.component)),[snapshot.inventory.adapters])
  return <main className="p10-page" aria-labelledby="runtime-title">
    <div className="p10-eyebrow">运行时 / 适配器 · P10</div>
    <div className="p10-heading-row"><div><h1 id="runtime-title">运行时</h1><p>模拟适配器清单与版本化配置草稿流程。密钥值永不返回浏览器。</p></div><div><strong>Config v{snapshot.inventory.configVersion}</strong> · {snapshot.inventory.environment}</div></div>
    {error===null?null:<p role="alert" className="p10-error">{error}</p>}
    <section className="p10-panel"><h2>适配器清单</h2><table className="p10-table"><thead><tr><th>组件</th><th>适配器</th><th>端点别名</th><th>已配置</th><th>健康</th><th>版本</th><th>上次检查</th><th>密钥来源</th></tr></thead><tbody>{snapshot.inventory.adapters.map((item)=><tr key={item.component}><td><strong>{item.label}</strong><br/><code>{item.component}</code></td><td><code>{item.adapter}</code></td><td><code>{item.endpointAlias}</code></td><td>{item.configured?'是':'否'}</td><td>{item.health}</td><td>{item.version}</td><td>{item.lastCheckAt}</td><td>{item.secret.source} · {item.secret.configured?'已配置':'未配置'}{item.secret.reference===undefined?'':<><br/><code>{item.secret.reference}</code></>}</td></tr>)}</tbody></table><p>{components.size}/10 个运行时组件已存在。</p></section>
    <section className="p10-panel"><h2>创建配置草稿</h2><p>可编辑字段仅为别名。URL、凭证、密钥值、项目范围与提升标志不属于此浏览器契约。</p><div className="p10-form"><label>组件<select value={component} disabled={busy} onChange={(event)=>onComponent(event.target.value as RuntimeComponent)}>{RUNTIME_COMPONENTS.map((item)=><option key={item} value={item}>{item}</option>)}</select></label><label>适配器别名<input value={adapter} disabled={busy} placeholder="mock-agent-model-v2" onChange={(event)=>onAdapter(event.target.value)}/></label><label>端点别名<input value={endpointAlias} disabled={busy} placeholder="agent-model-candidate" onChange={(event)=>onEndpointAlias(event.target.value)}/></label><button type="button" disabled={busy||(adapter.trim()===''&&endpointAlias.trim()==='')} onClick={onCreate}>创建草稿</button></div></section>
    <section className="p10-panel"><h2>草稿</h2>{snapshot.drafts.length===0?<p>暂无配置草稿。</p>:<table className="p10-table"><thead><tr><th>草稿</th><th>基础版本</th><th>状态</th><th>已保存</th><th>评测</th><th>合格</th><th /></tr></thead><tbody>{snapshot.drafts.map((draft)=><tr key={draft.draftId} data-selected={selected?.draftId===draft.draftId}><td><code>{draft.draftId}</code></td><td>v{draft.baseVersion}</td><td>{draft.status}</td><td>{draft.savedVersion===undefined?'—':`v${draft.savedVersion}`}</td><td>{draft.evalResult?.status??'—'}</td><td>{draft.eligibleForPromote?'是':'否'}</td><td><button type="button" onClick={()=>onSelect(draft)}>查看</button></td></tr>)}</tbody></table>}</section>
    {selected===undefined?null:<section className="p10-panel" data-draft={selected.draftId}><div className="p10-heading-row"><div><h2>配置草稿流程</h2><p><code>草稿 → 校验 → 差异 → 保存 → 版本提升 → 评测 → 可提升</code></p></div><strong>{selected.status}</strong></div><div className="p10-actions">{selected.status==='DRAFT'?<button type="button" disabled={busy} onClick={()=>onAction('validate',selected.draftId)}>校验</button>:null}{selected.status==='VALIDATED'?<button type="button" disabled={busy||errors>0} onClick={()=>onAction('save',selected.draftId)}>保存 &amp; 提升版本</button>:null}{selected.status==='SAVED'?<button type="button" disabled={busy} onClick={()=>onAction('eval',selected.draftId)}>运行评测</button>:null}</div><h3>校验</h3>{selected.validationIssues.length===0?<p>无校验问题。</p>:<ul>{selected.validationIssues.map((item)=><li key={`${item.code}-${item.component??'global'}`}>{item.severity} · {item.code} · {item.message}</li>)}</ul>}<h3>差异</h3>{selected.diff.length===0?<p>暂未生成差异。</p>:<table className="p10-table"><thead><tr><th>组件</th><th>字段</th><th>变更前</th><th>变更后</th></tr></thead><tbody>{selected.diff.map((item)=><tr key={`${item.component}-${item.field}`}><td>{item.component}</td><td>{item.field}</td><td><code>{item.before}</code></td><td><code>{item.after}</code></td></tr>)}</tbody></table>}<h3>评测 / 合格性</h3><p>评测: <strong>{selected.evalResult?.status??'未运行'}</strong> · 可提升: <strong>{selected.eligibleForPromote?'是':'否'}</strong></p>{selected.evalResult===undefined?null:<ul>{selected.evalResult.checks.map((item)=><li key={item.name}>{item.passed?'通过':'未通过'} · {item.name} · {item.detail}</li>)}</ul>}<p className="p10-note">P10 特意不提供提升操作。P11 负责统一基准评测/发布门禁。</p></section>}
  </main>
}

async function load(client:P10ApiClient):Promise<RuntimeSnapshot>{const[inventory,drafts]=await Promise.all([client.getRuntimeInventory(),client.listRuntimeConfigDrafts()]);return{inventory,drafts,selectedDraft:drafts[0]}}
function messageOf(reason:unknown):string{return reason instanceof Error?reason.message:String(reason)}
